-- ==============================================================================
-- AGROHEAL PRODUCTION SCHEMA DUMP FOR DEV MIGRATION
-- Generated at: 2026-09-10T21:53:07.016Z
-- ==============================================================================

DO $$ BEGIN
  CREATE TYPE public.withdrawal_status AS ENUM ('pending', 'success', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Table: public."audit_events"
CREATE TABLE IF NOT EXISTS public."audit_events" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid,
  "action" text NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" text,
  "payload" jsonb DEFAULT '{}'::jsonb,
  "ip_address" text,
  "user_agent" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public."checkout"
CREATE TABLE IF NOT EXISTS public."checkout" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "status" text DEFAULT ''::text,
  "first_name" text DEFAULT ''::text,
  "last_name" text DEFAULT ''::text,
  "email" text DEFAULT ''::text,
  "phone" text DEFAULT ''::text,
  "amount" text DEFAULT ''::text,
  "payment_method" text DEFAULT ''::text,
  "user_id" uuid,
  "transaction_ref" text,
  "project_category" text DEFAULT 'Gingertown'::text
);

-- Table: public."course_lessons"
CREATE TABLE IF NOT EXISTS public."course_lessons" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "module_id" uuid NOT NULL,
  "title" text NOT NULL,
  "video_url" text,
  "content" text,
  "duration_minutes" integer DEFAULT 10,
  "sequence_order" integer DEFAULT 1 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public."course_modules"
CREATE TABLE IF NOT EXISTS public."course_modules" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "course_id" uuid NOT NULL,
  "title" text NOT NULL,
  "sequence_order" integer DEFAULT 1 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public."courses"
CREATE TABLE IF NOT EXISTS public."courses" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "description" text,
  "thumbnail_url" text,
  "category" text DEFAULT 'Organic Farming'::text NOT NULL,
  "is_published" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public."existing_users_data"
CREATE TABLE IF NOT EXISTS public."existing_users_data" (
  "id" bigint NOT NULL,
  "RegNumber" text,
  "Fname" text,
  "Lname" text,
  "Email" text,
  "ContactNo" text,
  "Password" text,
  "Status" text,
  "Activation" text,
  "UserStatus" text,
  "payStatus" text,
  "whatsApp" text,
  "seedType" text,
  "Refer" text,
  "acctNo" text,
  "bankName" text,
  "Balance" numeric,
  "Amount" numeric,
  "Amount2" numeric,
  "payDate" timestamp without time zone,
  "payDate2" timestamp without time zone,
  "Address" text,
  "busStop" text,
  "State" text,
  "Lga" text,
  "RegDate" timestamp without time zone,
  "auth_id" uuid
);

-- Table: public."farm_expenses"
CREATE TABLE IF NOT EXISTS public."farm_expenses" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "farm_id" uuid NOT NULL,
  "category" text NOT NULL,
  "amount" numeric DEFAULT 0 NOT NULL,
  "description" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "created_by" uuid,
  "created_by_name" text,
  "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()),
  "updated_by" uuid,
  "updated_by_name" text
);

-- Table: public."farm_groups"
CREATE TABLE IF NOT EXISTS public."farm_groups" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "coordinator_id" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "project_category" text DEFAULT 'Gingertown'::text
);

-- Table: public."farm_records"
CREATE TABLE IF NOT EXISTS public."farm_records" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "farm_id" uuid NOT NULL,
  "name" text NOT NULL,
  "email" text,
  "phone" text,
  "farm_slots" integer DEFAULT 0,
  "absentee_fine" text DEFAULT 0,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "months_farm_setup" text DEFAULT 0 NOT NULL,
  "months_farm_support" text DEFAULT 0 NOT NULL,
  "project_category" text DEFAULT 'Gingertown'::text,
  "created_by" uuid,
  "created_by_name" text,
  "updated_by" uuid,
  "updated_by_name" text
);

-- Table: public."farm_sales"
CREATE TABLE IF NOT EXISTS public."farm_sales" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "farm_id" uuid NOT NULL,
  "produce_name" text NOT NULL,
  "quantity" numeric DEFAULT 1 NOT NULL,
  "unit" text DEFAULT 'kg'::text NOT NULL,
  "unit_price" numeric DEFAULT 0 NOT NULL,
  "amount" numeric NOT NULL,
  "buyer_name" text,
  "sales_channel" text DEFAULT 'Offtaker'::text,
  "sale_date" date DEFAULT CURRENT_DATE NOT NULL,
  "description" text,
  "created_by" uuid,
  "created_by_name" text,
  "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  "updated_by" uuid,
  "updated_by_name" text
);

-- Table: public."kin_details"
CREATE TABLE IF NOT EXISTS public."kin_details" (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "user_id" uuid NOT NULL,
  "kin_name" text NOT NULL,
  "kin_address" text NOT NULL,
  "kin_number" text NOT NULL,
  "date_created" timestamp with time zone DEFAULT now() NOT NULL,
  "date_updated" timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public."other_payments"
CREATE TABLE IF NOT EXISTS public."other_payments" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "payment_type" text NOT NULL,
  "months" integer NOT NULL,
  "slots" integer NOT NULL,
  "amount" numeric NOT NULL,
  "status" text DEFAULT 'pending'::text,
  "transaction_ref" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "subscription_id" uuid,
  "project_category" text DEFAULT 'Gingertown'::text
);

-- Table: public."profiles"
CREATE TABLE IF NOT EXISTS public."profiles" (
  "id" uuid NOT NULL,
  "full_name" text,
  "referral_code" text,
  "referred_by" uuid,
  "affiliate_balance" numeric DEFAULT 0,
  "created_at" timestamp without time zone DEFAULT now(),
  "courses" numeric DEFAULT '22'::numeric,
  "total_referrals" numeric DEFAULT '0'::numeric,
  "referral_earnings" integer DEFAULT 0,
  "phone" text,
  "slot_bonus" numeric DEFAULT 0,
  "member_id" text,
  "role" text DEFAULT 'member'::text,
  "email" text,
  "sponsor_id" uuid,
  "placement_parent_id" uuid,
  "matrix_depth" integer DEFAULT 1,
  "matrix_position" integer DEFAULT 1,
  "kyc_status" text DEFAULT 'unverified'::text,
  "bank_name" text,
  "bank_account_number" text,
  "bank_account_name" text,
  "bank_code" text,
  "green_card_fee" numeric DEFAULT 2000.00 NOT NULL,
  "wallet_balance" numeric DEFAULT 0
);

-- Table: public."slot_subscriptions"
CREATE TABLE IF NOT EXISTS public."slot_subscriptions" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid,
  "checkout_id" bigint,
  "status" text DEFAULT 'active'::text,
  "amount" integer DEFAULT 500,
  "next_payment_date" timestamp with time zone,
  "last_payment_date" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now(),
  "slots" integer DEFAULT 1,
  "slotprice" integer DEFAULT 2000,
  "monthly_pay" integer,
  "project_category" text DEFAULT 'Gingertown'::text
);

-- Table: public."subscription_payments"
CREATE TABLE IF NOT EXISTS public."subscription_payments" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "subscription_id" uuid,
  "user_id" uuid,
  "amount" integer,
  "transaction_ref" text,
  "status" text,
  "created_at" timestamp with time zone DEFAULT now()
);

-- Table: public."subscriptions"
CREATE TABLE IF NOT EXISTS public."subscriptions" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid,
  "plan" text DEFAULT 'platform'::text,
  "status" text DEFAULT 'active'::text,
  "started_at" timestamp without time zone DEFAULT now(),
  "expires_at" timestamp without time zone
);

-- Table: public."system_configs"
CREATE TABLE IF NOT EXISTS public."system_configs" (
  "key" text NOT NULL,
  "value" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now(),
  "updated_by" uuid
);

-- Table: public."user_lesson_progress"
CREATE TABLE IF NOT EXISTS public."user_lesson_progress" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "lesson_id" uuid NOT NULL,
  "completed" boolean DEFAULT false NOT NULL,
  "completed_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public."wallet_ledger"
CREATE TABLE IF NOT EXISTS public."wallet_ledger" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "amount" numeric NOT NULL,
  "balance_after" numeric,
  "entry_type" text NOT NULL,
  "category" text NOT NULL,
  "status" text DEFAULT 'AVAILABLE'::text NOT NULL,
  "reference_id" text,
  "description" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Table: public."withdrawals"
CREATE TABLE IF NOT EXISTS public."withdrawals" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "reference" text NOT NULL,
  "amount" numeric NOT NULL,
  "status" text DEFAULT 'queued'::text NOT NULL,
  "bank_name" text NOT NULL,
  "bank_code" text NOT NULL,
  "account_number" text NOT NULL,
  "account_name" text NOT NULL,
  "provider" text DEFAULT 'flutterwave'::text NOT NULL,
  "provider_response" jsonb,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

DO $$ BEGIN
  ALTER TABLE public."audit_events" ADD CONSTRAINT "audit_events_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."checkout" ADD CONSTRAINT "checkout_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."course_lessons" ADD CONSTRAINT "course_lessons_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."course_modules" ADD CONSTRAINT "course_modules_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."courses" ADD CONSTRAINT "courses_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."courses" ADD CONSTRAINT "courses_slug_key" UNIQUE (slug);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."existing_users_data" ADD CONSTRAINT "existing_users_data_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."farm_expenses" ADD CONSTRAINT "farm_expenses_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."farm_groups" ADD CONSTRAINT "farm_groups_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."farm_groups" ADD CONSTRAINT "farm_groups_slug_key" UNIQUE (slug);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."farm_records" ADD CONSTRAINT "farm_records_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."farm_sales" ADD CONSTRAINT "farm_sales_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."kin_details" ADD CONSTRAINT "kin_details_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."other_payments" ADD CONSTRAINT "other_payments_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_id_key" UNIQUE (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."slot_subscriptions" ADD CONSTRAINT "slot_subscriptions_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."subscription_payments" ADD CONSTRAINT "subscription_payments_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."subscriptions" ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."subscriptions" ADD CONSTRAINT "subscriptions_user_id_key" UNIQUE (user_id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."system_configs" ADD CONSTRAINT "system_configs_pkey" PRIMARY KEY (key);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."user_lesson_progress" ADD CONSTRAINT "user_lesson_progress_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."user_lesson_progress" ADD CONSTRAINT "user_lesson_progress_user_id_lesson_id_key" UNIQUE (user_id, lesson_id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."wallet_ledger" ADD CONSTRAINT "wallet_ledger_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."withdrawals" ADD CONSTRAINT "withdrawals_pkey" PRIMARY KEY (id);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."withdrawals" ADD CONSTRAINT "withdrawals_reference_key" UNIQUE (reference);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."kin_details" ADD CONSTRAINT "kin_details_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."course_modules" ADD CONSTRAINT "course_modules_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."other_payments" ADD CONSTRAINT "other_payments_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "public"."slot_subscriptions" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."course_lessons" ADD CONSTRAINT "course_lessons_module_id_fkey" FOREIGN KEY ("module_id") REFERENCES "public"."course_modules" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."slot_subscriptions" ADD CONSTRAINT "slot_subscriptions_checkout_id_fkey" FOREIGN KEY ("checkout_id") REFERENCES "public"."checkout" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."subscription_payments" ADD CONSTRAINT "subscription_payments_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "public"."slot_subscriptions" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."farm_records" ADD CONSTRAINT "farm_records_farm_id_fkey" FOREIGN KEY ("farm_id") REFERENCES "public"."farm_groups" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."farm_expenses" ADD CONSTRAINT "farm_expenses_farm_id_fkey" FOREIGN KEY ("farm_id") REFERENCES "public"."farm_groups" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."user_lesson_progress" ADD CONSTRAINT "user_lesson_progress_lesson_id_fkey" FOREIGN KEY ("lesson_id") REFERENCES "public"."course_lessons" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public."farm_sales" ADD CONSTRAINT "farm_sales_farm_id_fkey" FOREIGN KEY ("farm_id") REFERENCES "public"."farm_groups" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX idx_checkout_user_status ON public.checkout USING btree (user_id, status);
CREATE INDEX idx_checkout_status_created ON public.checkout USING btree (status, created_at);
CREATE INDEX idx_other_payments_user ON public.other_payments USING btree (user_id);
CREATE INDEX idx_farm_groups_slug ON public.farm_groups USING btree (slug);
CREATE INDEX idx_farm_groups_coordinator_id ON public.farm_groups USING btree (coordinator_id);
CREATE INDEX idx_profiles_role ON public.profiles USING btree (role);
CREATE INDEX idx_profiles_sponsor_id ON public.profiles USING btree (sponsor_id);
CREATE INDEX idx_profiles_placement_parent_id ON public.profiles USING btree (placement_parent_id);
CREATE INDEX idx_profiles_email ON public.profiles USING btree (lower(email));
CREATE INDEX idx_profiles_member_id ON public.profiles USING btree (member_id);
CREATE INDEX idx_profiles_referred_by ON public.profiles USING btree (referred_by);
CREATE INDEX idx_profiles_placement_parent ON public.profiles USING btree (placement_parent_id);
CREATE INDEX idx_profiles_referral_code ON public.profiles USING btree (referral_code);
CREATE INDEX idx_withdrawals_user_created_at ON public.withdrawals USING btree (user_id, created_at DESC);
CREATE INDEX idx_withdrawals_status ON public.withdrawals USING btree (status);
CREATE INDEX idx_slot_subscriptions_user_status ON public.slot_subscriptions USING btree (user_id, status);
CREATE INDEX kin_details_user_id_idx ON public.kin_details USING btree (user_id);
CREATE INDEX idx_wallet_ledger_user_id ON public.wallet_ledger USING btree (user_id);
CREATE INDEX idx_wallet_ledger_category ON public.wallet_ledger USING btree (category);
CREATE INDEX idx_wallet_ledger_status ON public.wallet_ledger USING btree (status);
CREATE INDEX idx_wallet_ledger_created_at ON public.wallet_ledger USING btree (created_at DESC);
CREATE INDEX idx_audit_events_action ON public.audit_events USING btree (action);
CREATE INDEX idx_audit_events_entity ON public.audit_events USING btree (entity_type, entity_id);
CREATE INDEX idx_audit_events_created_at ON public.audit_events USING btree (created_at DESC);
CREATE INDEX idx_farm_records_farm_id ON public.farm_records USING btree (farm_id);
CREATE INDEX idx_farm_records_email ON public.farm_records USING btree (lower(email));
CREATE INDEX idx_farm_sales_farm_id ON public.farm_sales USING btree (farm_id);
CREATE INDEX idx_farm_sales_sale_date ON public.farm_sales USING btree (sale_date);

CREATE OR REPLACE FUNCTION public.check_email_exists(email_input text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM auth.users
    WHERE email = lower(email_input)
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_slot_bonus(user_id uuid, amount numeric)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE profiles
  SET slot_bonus = COALESCE(slot_bonus, 0) + amount
  WHERE id = user_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.prevent_role_self_escalation()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    BEGIN
      -- Allow default 'member' role on INSERT
      IF TG_OP = 'INSERT' AND (NEW.role = 'member' OR NEW.role IS NULL) THEN
        NEW.role := 'member';
        RETURN NEW;
      END IF;

      IF NEW.role IS DISTINCT FROM COALESCE(OLD.role, 'member') THEN
        IF auth.role() = 'service_role' OR auth.role() = 'postgres' THEN
          RETURN NEW;
        END IF;
        IF is_admin(auth.uid()) THEN
          RETURN NEW;
        END IF;
        RAISE EXCEPTION 'Not authorized to change role';
      END IF;
      RETURN NEW;
    END;
    $function$
;

CREATE OR REPLACE FUNCTION public.increment_referral_earnings(referrer_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE profiles
  SET
    referral_earnings = referral_earnings + 1000,
    total_referrals = total_referrals + 1
  WHERE id = referrer_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_category_slots(target_user_id uuid, target_category text)
 RETURNS numeric
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT COALESCE(SUM(slots), 0)
  FROM slot_subscriptions
  WHERE user_id = target_user_id
    AND status = 'active'
    AND COALESCE(project_category, 'Gingertown') = target_category;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_category_payments(target_user_id uuid, target_category text)
 RETURNS TABLE(amount numeric, payment_type text)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT amount, payment_type
  FROM other_payments
  WHERE user_id = target_user_id
    AND status = 'success'
    AND COALESCE(project_category, 'Gingertown') = target_category;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_ids_by_emails(emails text[])
 RETURNS TABLE(user_id uuid, email text)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT id AS user_id, email 
  FROM auth.users 
  WHERE lower(email) = ANY(SELECT lower(e) FROM unnest(emails) AS e);
$function$
;

CREATE OR REPLACE FUNCTION public.get_users_category_payments_batch(target_user_ids uuid[], target_category text)
 RETURNS TABLE(user_id uuid, payment_type text, created_at timestamp with time zone, slots numeric, amount numeric, months text, project_category text)
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT user_id, payment_type, created_at, slots, amount, months, project_category
  FROM other_payments
  WHERE user_id = ANY(target_user_ids)
    AND status = 'success'
    AND COALESCE(project_category, 'Gingertown') = target_category;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_slot_bonus()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    referrer_id UUID;
BEGIN
    -- 1. Find the referrer
    SELECT referred_by INTO referrer_id FROM profiles WHERE id = NEW.user_id;
    
    -- 2. Debug: Only proceed if a referrer exists
    IF referrer_id IS NOT NULL THEN
        -- We cast slots to numeric just in case it's stored as text
        UPDATE profiles 
        SET slot_bonus = COALESCE(slot_bonus, 0) + (500 * COALESCE(NEW.slots, '0')::NUMERIC)
        WHERE id = referrer_id;
    END IF;
    
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.link_existing_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- wrap everything in exception so NOTHING can block signup
  BEGIN
    UPDATE existing_users_data
    SET auth_id = NEW.id
    WHERE "Email" = NEW.email AND auth_id IS NULL;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  BEGIN
    INSERT INTO profiles (id, full_name, created_at)
    SELECT
      NEW.id,
      COALESCE(e."Fname" || ' ' || e."Lname", NEW.email),
      NOW()
    FROM existing_users_data e
    WHERE e."Email" = NEW.email
    ON CONFLICT (id) DO UPDATE
    SET full_name = EXCLUDED.full_name;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  BEGIN
    INSERT INTO subscriptions (user_id, status, plan, started_at, expires_at)
    SELECT
      NEW.id,
      CASE WHEN e."payStatus" = '1' THEN 'active' ELSE 'inactive' END,
      'default',
      NOW(),
      NOW() + INTERVAL '1 year'
    FROM existing_users_data e
    WHERE e."Email" = NEW.email
    ON CONFLICT (user_id) DO UPDATE
    SET status = EXCLUDED.status;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  RETURN NEW; -- always return NEW no matter what
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    declare
      new_code text;
      referrer_id uuid;
      incoming_ref text;
    begin
      select string_agg(
        substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', (random() * 36)::int + 1, 1),
        ''
      )
      into new_code
      from generate_series(1, 6);

      incoming_ref := new.raw_user_meta_data->>'referral_code';

      if incoming_ref is not null and trim(incoming_ref) != '' then
        select id into referrer_id
        from public.profiles
        where referral_code = trim(incoming_ref);
      end if;

      -- Leave referrer_id as NULL if none provided (awaiting official coordinator details)

      insert into public.profiles (
        id, email, full_name, referral_code, referred_by, role, created_at,
        affiliate_balance, slot_bonus, referral_earnings, total_referrals
      )
      values (
        new.id,
        new.email,
        coalesce(nullif(trim(new.raw_user_meta_data->>'full_name'), ''), new.email, 'AgroHeal Member'),
        new_code,
        referrer_id,
        'member',
        now(),
        0, 0, 0, 0
      )
      on conflict (id) do update set
        email = coalesce(excluded.email, public.profiles.email),
        full_name = case when public.profiles.full_name is null or public.profiles.full_name = '' then excluded.full_name else public.profiles.full_name end;

      return new;
    end;
    $function$
;

CREATE OR REPLACE FUNCTION public.get_or_create_green_card_member_id(p_user_id uuid, p_join_year integer)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  existing text;
  seq_val bigint;
  new_id text;
begin
  select member_id into existing from profiles where id = p_user_id;
  if existing is not null then
    return existing;
  end if;

  seq_val := nextval('green_card_member_seq');
  new_id := 'AGC-' || lpad(seq_val::text, 5, '0') || '-' || p_join_year::text;

  update profiles set member_id = new_id where id = p_user_id;

  return new_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin(p_user_id uuid DEFAULT auth.uid())
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
      SELECT EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = p_user_id AND role IN ('admin', 'super_admin', 'support')
      ) OR EXISTS (
        SELECT 1 FROM auth.users
        WHERE id = p_user_id AND email = 'developerelijah360@gmail.com'
      );
    $function$
;

CREATE OR REPLACE FUNCTION public.handle_update_user_email()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.email is distinct from old.email then
    update public.profiles
    set email = new.email
    where id = new.id;
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_admin_members()
 RETURNS TABLE(id uuid, email text, full_name text, phone text, member_id text, referral_code text, referred_by uuid, role text, created_at timestamp with time zone)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
  select
    p.id,
    coalesce(nullif(p.email, ''), u.email, '') as email,
    p.full_name,
    coalesce(p.phone, '') as phone,
    p.member_id,
    p.referral_code,
    p.referred_by,
    coalesce(p.role, 'user') as role,
    p.created_at
  from public.profiles p
  left join auth.users u on u.id = p.id
  order by p.created_at desc;
$function$
;

CREATE OR REPLACE FUNCTION public.get_green_card_community_size(leader_id uuid)
 RETURNS integer
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select 1 + count(*)
  from profiles p
  join subscriptions s on s.user_id = p.id
  where p.referred_by = leader_id
    and s.plan = 'green_card'
    and s.status = 'active';
$function$
;

CREATE OR REPLACE FUNCTION public.get_member_details_by_email(email_input text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_user_id UUID;
  v_full_name TEXT;
  v_phone TEXT;
  v_total_slots NUMERIC;
BEGIN
  SELECT id INTO v_user_id FROM auth.users WHERE email = email_input LIMIT 1;

  IF v_user_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT full_name, phone INTO v_full_name, v_phone
  FROM profiles WHERE id = v_user_id;

  SELECT COALESCE(SUM(CAST(slots AS NUMERIC)), 0) INTO v_total_slots
  FROM slot_subscriptions WHERE user_id = v_user_id;

  RETURN json_build_object(
    'full_name', v_full_name,
    'phone', v_phone,
    'total_slots', v_total_slots
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.admin_activate_green_card(p_user_id uuid, p_credit_referrer boolean DEFAULT true)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
declare
  v_member_id text;
  v_expires_at timestamptz;
  v_referrer_id uuid;
  v_is_first_activation boolean;
  v_tx_ref text;
begin
  -- Check if already has a subscription
  select not exists (
    select 1 from public.subscriptions where user_id = p_user_id and plan = 'green_card'
  ) into v_is_first_activation;

  -- Calculate 1 year expiry from now
  v_expires_at := now() + interval '1 year';

  -- Upsert active Green Card subscription
  delete from public.subscriptions where user_id = p_user_id and plan = 'green_card';
  insert into public.subscriptions (user_id, plan, status, started_at, expires_at)
  values (p_user_id, 'green_card', 'active', now(), v_expires_at);

  -- Assign / Retrieve Member ID
  v_member_id := public.get_or_create_green_card_member_id(p_user_id, extract(year from now())::int);

  -- Record payment in other_payments log
  v_tx_ref := 'ADMIN_GC_' || floor(extract(epoch from now()))::text || '_' || substr(md5(random()::text), 1, 4);
  insert into public.other_payments (
    user_id,
    payment_type,
    amount,
    slots,
    project_category,
    status,
    transaction_ref,
    created_at
  )
  values (
    p_user_id,
    'green_card_offline',
    1000,
    0,
    'Green Card Membership (Admin Offline Activation)',
    'success',
    v_tx_ref,
    now()
  );

  -- Credit referral earnings if first activation
  if p_credit_referrer and v_is_first_activation then
    select referred_by into v_referrer_id from public.profiles where id = p_user_id;
    if v_referrer_id is not null then
      begin
        perform public.increment_referral_earnings(v_referrer_id, 500);
      exception when others then
        null;
      end;
    end if;
  end if;

  return jsonb_build_object(
    'success', true,
    'member_id', v_member_id,
    'expires_at', v_expires_at
  );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_or_create_referral_code(p_user_id uuid)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  existing text;
  new_code text;
begin
  select referral_code into existing from profiles where id = p_user_id;
  if existing is not null then
    return existing;
  end if;

  -- Same 6-character alphanumeric style already used when profiles are
  -- first created (see verify-payment's Math.random().toString(36) code).
  select string_agg(
    substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', (random() * 36)::int + 1, 1),
    ''
  )
  into new_code
  from generate_series(1, 6);

  update profiles set referral_code = new_code where id = p_user_id;

  return new_code;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_email_by_id(user_id uuid)
 RETURNS text
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
  select email
  from auth.users
  where id = user_id
  limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_id_by_email(p_email text)
 RETURNS uuid
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
  select id
  from auth.users
  where lower(email) = lower(p_email)
  limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.get_green_card_community_members(leader_id uuid)
 RETURNS TABLE(id uuid, full_name text, member_id text, joined_at timestamp with time zone)
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select p.id, p.full_name, p.member_id, s.started_at as joined_at
  from profiles p
  join subscriptions s on s.user_id = p.id
  where p.referred_by = leader_id
    and s.plan = 'green_card'
    and s.status = 'active'
  order by s.started_at asc;
$function$
;

CREATE OR REPLACE FUNCTION public.subscribe_with_wallet_balance(p_user_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    DECLARE
      v_current_earnings NUMERIC;
      v_already_subscribed BOOLEAN;
      v_sub_id UUID;
    BEGIN
      -- Check current earnings
      SELECT COALESCE(referral_earnings, 0) INTO v_current_earnings
      FROM public.profiles
      WHERE id = p_user_id;

      IF v_current_earnings IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'Profile not found.');
      END IF;

      IF v_current_earnings < 10000 THEN
        RETURN jsonb_build_object(
          'success', false, 
          'message', 'Insufficient wallet balance. Minimum ₦10,000 required to activate project subscription from wallet.'
        );
      END IF;

      -- Check if already subscribed
      SELECT EXISTS (
        SELECT 1 FROM public.subscriptions 
        WHERE user_id = p_user_id AND status = 'active' AND (expires_at IS NULL OR expires_at > NOW())
      ) INTO v_already_subscribed;

      IF v_already_subscribed THEN
        RETURN jsonb_build_object('success', false, 'message', 'User already has an active project subscription.');
      END IF;

      -- Deduct ₦10,000 from referral earnings and wallet balance
      UPDATE public.profiles
      SET 
        referral_earnings = referral_earnings - 10000,
        wallet_balance = GREATEST(0, COALESCE(wallet_balance, 0) - 10000)
      WHERE id = p_user_id;

      -- Record transaction in wallet_ledger
      INSERT INTO public.wallet_ledger (
        user_id, amount, balance_after, category, status, reference_id, description, entry_type
      ) VALUES (
        p_user_id,
        -10000,
        v_current_earnings - 10000,
        'SUBSCRIPTION',
        'AVAILABLE',
        'WAL-SUB-' || substr(md5(random()::text), 1, 10),
        'Project subscription activated using ₦10,000 wallet credit',
        'DEBIT'
      );

      -- Activate lifetime Green Card subscription (100 years)
      INSERT INTO public.subscriptions (
        user_id, plan, status, started_at, expires_at, slots
      ) VALUES (
        p_user_id,
        'green_card',
        'active',
        NOW(),
        NOW() + INTERVAL '100 years',
        1
      )
      RETURNING id INTO v_sub_id;

      RETURN jsonb_build_object(
        'success', true, 
        'message', 'Project subscription successfully activated using wallet balance!',
        'subscription_id', v_sub_id,
        'remaining_earnings', v_current_earnings - 10000
      );
    END;
    $function$
;

CREATE OR REPLACE FUNCTION public.pay_checkout_with_wallet(p_user_id uuid, p_checkout_id uuid, p_amount numeric, p_slots integer, p_slot_price numeric, p_category text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    DECLARE
      v_current_balance NUMERIC;
      v_ref TEXT;
      v_sub_id UUID;
    BEGIN
      -- Check current earnings/balance
      SELECT COALESCE(referral_earnings, 0) INTO v_current_balance
      FROM public.profiles
      WHERE id = p_user_id;

      IF v_current_balance IS NULL THEN
        RETURN jsonb_build_object('success', false, 'message', 'User profile not found.');
      END IF;

      IF v_current_balance < p_amount THEN
        RETURN jsonb_build_object(
          'success', false, 
          'message', 'Insufficient wallet balance. You have ₦' || v_current_balance || ' but order requires ₦' || p_amount || '.'
        );
      END IF;

      -- Generate reference
      v_ref := 'WAL-PAY-' || substr(md5(random()::text), 1, 10);

      -- Deduct from wallet balance and referral earnings
      UPDATE public.profiles
      SET 
        referral_earnings = referral_earnings - p_amount,
        wallet_balance = GREATEST(0, COALESCE(wallet_balance, 0) - p_amount)
      WHERE id = p_user_id;

      -- Update checkout record
      UPDATE public.checkout
      SET 
        status = 'paid',
        payment_method = 'wallet',
        transaction_ref = v_ref
      WHERE id = p_checkout_id AND user_id = p_user_id;

      -- Record double-entry debit in wallet_ledger
      INSERT INTO public.wallet_ledger (
        user_id, amount, balance_after, category, status, reference_id, description, entry_type
      ) VALUES (
        p_user_id,
        -p_amount,
        v_current_balance - p_amount,
        'SLOT_PURCHASE',
        'AVAILABLE',
        v_ref,
        'Reinvestment: ' || p_slots || ' farm slot(s) purchased via wallet balance',
        'DEBIT'
      );

      -- Create active slot subscription
      INSERT INTO public.slot_subscriptions (
        user_id,
        checkout_id,
        amount,
        slotprice,
        status,
        slots,
        last_payment_date,
        next_payment_date,
        project_category
      ) VALUES (
        p_user_id,
        p_checkout_id,
        p_amount,
        p_slot_price,
        'active',
        p_slots,
        NOW(),
        NOW() + INTERVAL '30 days',
        p_category
      ) RETURNING id INTO v_sub_id;

      RETURN jsonb_build_object(
        'success', true,
        'message', 'Payment successful! ' || p_slots || ' farm slot(s) activated from your wallet balance.',
        'transaction_ref', v_ref,
        'remaining_balance', v_current_balance - p_amount,
        'subscription_id', v_sub_id
      );
    END;
    $function$
;

DROP TRIGGER IF EXISTS "on_slot_purchased" ON public."slot_subscriptions";
CREATE TRIGGER "on_slot_purchased" AFTER INSERT ON public."slot_subscriptions" FOR EACH ROW EXECUTE FUNCTION handle_new_slot_bonus();

DROP TRIGGER IF EXISTS "trg_prevent_role_self_escalation" ON public."profiles";
CREATE TRIGGER "trg_prevent_role_self_escalation" BEFORE INSERT ON public."profiles" FOR EACH ROW EXECUTE FUNCTION prevent_role_self_escalation();

DROP TRIGGER IF EXISTS "trg_prevent_role_self_escalation" ON public."profiles";
CREATE TRIGGER "trg_prevent_role_self_escalation" BEFORE UPDATE ON public."profiles" FOR EACH ROW EXECUTE FUNCTION prevent_role_self_escalation();

ALTER TABLE public."audit_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."checkout" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."course_lessons" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."course_modules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."courses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."existing_users_data" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."farm_expenses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."farm_groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."farm_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."farm_sales" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."kin_details" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."other_payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."slot_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."subscription_payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."system_configs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_lesson_progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."wallet_ledger" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."withdrawals" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own data" ON public."existing_users_data";
CREATE POLICY "Users can view own data" ON public."existing_users_data" FOR SELECT TO public USING ((auth_id = auth.uid()));

DROP POLICY IF EXISTS "Users can insert own subscriptions" ON public."slot_subscriptions";
CREATE POLICY "Users can insert own subscriptions" ON public."slot_subscriptions" FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can read own subscriptions" ON public."slot_subscriptions";
CREATE POLICY "Users can read own subscriptions" ON public."slot_subscriptions" FOR SELECT TO authenticated USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can update own subscriptions" ON public."slot_subscriptions";
CREATE POLICY "Users can update own subscriptions" ON public."slot_subscriptions" FOR UPDATE TO authenticated USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can insert own payments" ON public."subscription_payments";
CREATE POLICY "Users can insert own payments" ON public."subscription_payments" FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can read own payments" ON public."subscription_payments";
CREATE POLICY "Users can read own payments" ON public."subscription_payments" FOR SELECT TO authenticated USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can manage own subscription" ON public."subscriptions";
CREATE POLICY "Users can manage own subscription" ON public."subscriptions" FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can manage own profile" ON public."profiles";
CREATE POLICY "Users can manage own profile" ON public."profiles" FOR ALL TO public USING ((auth.uid() = id)) WITH CHECK ((auth.uid() = id));

DROP POLICY IF EXISTS "Authenticated users can read all profiles" ON public."profiles";
CREATE POLICY "Authenticated users can read all profiles" ON public."profiles" FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Users can view own withdrawals" ON public."withdrawals";
CREATE POLICY "Users can view own withdrawals" ON public."withdrawals" FOR SELECT TO public USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Authenticated users can view farm groups" ON public."farm_groups";
CREATE POLICY "Authenticated users can view farm groups" ON public."farm_groups" FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Coordinator can update their farm group" ON public."farm_groups";
CREATE POLICY "Coordinator can update their farm group" ON public."farm_groups" FOR UPDATE TO public USING ((coordinator_id = auth.uid()));

DROP POLICY IF EXISTS "Coordinator can delete their farm group" ON public."farm_groups";
CREATE POLICY "Coordinator can delete their farm group" ON public."farm_groups" FOR DELETE TO public USING ((coordinator_id = auth.uid()));

DROP POLICY IF EXISTS "Authenticated users can create farm group" ON public."farm_groups";
CREATE POLICY "Authenticated users can create farm group" ON public."farm_groups" FOR INSERT TO public WITH CHECK ((coordinator_id = auth.uid()));

DROP POLICY IF EXISTS "Authenticated users can view farm records" ON public."farm_records";
CREATE POLICY "Authenticated users can view farm records" ON public."farm_records" FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Coordinator can insert farm records" ON public."farm_records";
CREATE POLICY "Coordinator can insert farm records" ON public."farm_records" FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1
   FROM farm_groups
  WHERE ((farm_groups.id = farm_records.farm_id) AND (farm_groups.coordinator_id = auth.uid())))));

DROP POLICY IF EXISTS "Coordinator can update farm records" ON public."farm_records";
CREATE POLICY "Coordinator can update farm records" ON public."farm_records" FOR UPDATE TO public USING ((EXISTS ( SELECT 1
   FROM farm_groups
  WHERE ((farm_groups.id = farm_records.farm_id) AND (farm_groups.coordinator_id = auth.uid())))));

DROP POLICY IF EXISTS "kin_delete_own" ON public."kin_details";
CREATE POLICY "kin_delete_own" ON public."kin_details" FOR DELETE TO public USING ((user_id = auth.uid()));

DROP POLICY IF EXISTS "Anyone can read system_configs" ON public."system_configs";
CREATE POLICY "Anyone can read system_configs" ON public."system_configs" FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Admins can update all profiles" ON public."profiles";
CREATE POLICY "Admins can update all profiles" ON public."profiles" FOR UPDATE TO public USING (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Coordinator can delete farm records" ON public."farm_records";
CREATE POLICY "Coordinator can delete farm records" ON public."farm_records" FOR DELETE TO public USING ((EXISTS ( SELECT 1
   FROM farm_groups
  WHERE ((farm_groups.id = farm_records.farm_id) AND (farm_groups.coordinator_id = auth.uid())))));

DROP POLICY IF EXISTS "Users can view their own other payments" ON public."other_payments";
CREATE POLICY "Users can view their own other payments" ON public."other_payments" FOR SELECT TO authenticated USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can insert their own other payments" ON public."other_payments";
CREATE POLICY "Users can insert their own other payments" ON public."other_payments" FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can update their own other payments" ON public."other_payments";
CREATE POLICY "Users can update their own other payments" ON public."other_payments" FOR UPDATE TO authenticated USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can view farm expenses" ON public."farm_expenses";
CREATE POLICY "Users can view farm expenses" ON public."farm_expenses" FOR SELECT TO public USING (((EXISTS ( SELECT 1
   FROM farm_records
  WHERE ((farm_records.farm_id = farm_expenses.farm_id) AND (farm_records.email = (auth.jwt() ->> 'email'::text))))) OR (EXISTS ( SELECT 1
   FROM farm_groups
  WHERE ((farm_groups.id = farm_expenses.farm_id) AND (farm_groups.coordinator_id = auth.uid()))))));

DROP POLICY IF EXISTS "Admins can modify system_configs" ON public."system_configs";
CREATE POLICY "Admins can modify system_configs" ON public."system_configs" FOR ALL TO public USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can view all profiles" ON public."profiles";
CREATE POLICY "Admins can view all profiles" ON public."profiles" FOR SELECT TO public USING (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Coordinators can manage farm expenses" ON public."farm_expenses";
CREATE POLICY "Coordinators can manage farm expenses" ON public."farm_expenses" FOR ALL TO public USING ((EXISTS ( SELECT 1
   FROM farm_groups
  WHERE ((farm_groups.id = farm_expenses.farm_id) AND (farm_groups.coordinator_id = auth.uid())))));

DROP POLICY IF EXISTS "Allow authenticated users full access to records" ON public."farm_records";
CREATE POLICY "Allow authenticated users full access to records" ON public."farm_records" FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated read all other_payments" ON public."other_payments";
CREATE POLICY "Allow authenticated read all other_payments" ON public."other_payments" FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Users can view own profile" ON public."profiles";
CREATE POLICY "Users can view own profile" ON public."profiles" FOR SELECT TO public USING ((auth.uid() = id));

DROP POLICY IF EXISTS "Users can update own basic info" ON public."profiles";
CREATE POLICY "Users can update own basic info" ON public."profiles" FOR UPDATE TO public USING ((auth.uid() = id)) WITH CHECK ((auth.uid() = id));

DROP POLICY IF EXISTS "Users can view own subscriptions" ON public."slot_subscriptions";
CREATE POLICY "Users can view own subscriptions" ON public."slot_subscriptions" FOR SELECT TO public USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can create own checkout" ON public."checkout";
CREATE POLICY "Users can create own checkout" ON public."checkout" FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Users can view own checkout" ON public."checkout";
CREATE POLICY "Users can view own checkout" ON public."checkout" FOR SELECT TO public USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "kin_select_own" ON public."kin_details";
CREATE POLICY "kin_select_own" ON public."kin_details" FOR SELECT TO public USING ((user_id = auth.uid()));

DROP POLICY IF EXISTS "kin_insert_own" ON public."kin_details";
CREATE POLICY "kin_insert_own" ON public."kin_details" FOR INSERT TO public WITH CHECK ((user_id = auth.uid()));

DROP POLICY IF EXISTS "kin_update_own" ON public."kin_details";
CREATE POLICY "kin_update_own" ON public."kin_details" FOR UPDATE TO public USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));

DROP POLICY IF EXISTS "Admins can manage slot_subscriptions" ON public."slot_subscriptions";
CREATE POLICY "Admins can manage slot_subscriptions" ON public."slot_subscriptions" FOR ALL TO public USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can manage other_payments" ON public."other_payments";
CREATE POLICY "Admins can manage other_payments" ON public."other_payments" FOR ALL TO public USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can manage subscriptions" ON public."subscriptions";
CREATE POLICY "Admins can manage subscriptions" ON public."subscriptions" FOR ALL TO public USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can manage all farm groups" ON public."farm_groups";
CREATE POLICY "Admins can manage all farm groups" ON public."farm_groups" FOR ALL TO authenticated USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can manage all farm records" ON public."farm_records";
CREATE POLICY "Admins can manage all farm records" ON public."farm_records" FOR ALL TO authenticated USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Allow authenticated users full access to expenses" ON public."farm_expenses";
CREATE POLICY "Allow authenticated users full access to expenses" ON public."farm_expenses" FOR ALL TO authenticated USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Users can view own wallet ledger" ON public."wallet_ledger";
CREATE POLICY "Users can view own wallet ledger" ON public."wallet_ledger" FOR SELECT TO public USING ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Admins can manage all wallet ledgers" ON public."wallet_ledger";
CREATE POLICY "Admins can manage all wallet ledgers" ON public."wallet_ledger" FOR ALL TO public USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can read audit events" ON public."audit_events";
CREATE POLICY "Admins can read audit events" ON public."audit_events" FOR SELECT TO public USING (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Green Card holders can view published courses" ON public."courses";
CREATE POLICY "Green Card holders can view published courses" ON public."courses" FOR SELECT TO public USING (((is_published = true) AND (EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND ((profiles.member_id IS NOT NULL) AND (profiles.member_id <> 'No ID Assigned'::text)))))));

DROP POLICY IF EXISTS "Green Card holders can view course modules" ON public."course_modules";
CREATE POLICY "Green Card holders can view course modules" ON public."course_modules" FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND ((profiles.member_id IS NOT NULL) AND (profiles.member_id <> 'No ID Assigned'::text))))));

DROP POLICY IF EXISTS "Green Card holders can view lessons" ON public."course_lessons";
CREATE POLICY "Green Card holders can view lessons" ON public."course_lessons" FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND ((profiles.member_id IS NOT NULL) AND (profiles.member_id <> 'No ID Assigned'::text))))));

DROP POLICY IF EXISTS "Users can manage own lesson progress" ON public."user_lesson_progress";
CREATE POLICY "Users can manage own lesson progress" ON public."user_lesson_progress" FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));

DROP POLICY IF EXISTS "Admins manage all courses" ON public."courses";
CREATE POLICY "Admins manage all courses" ON public."courses" FOR ALL TO public USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins manage all modules" ON public."course_modules";
CREATE POLICY "Admins manage all modules" ON public."course_modules" FOR ALL TO public USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins manage all lessons" ON public."course_lessons";
CREATE POLICY "Admins manage all lessons" ON public."course_lessons" FOR ALL TO public USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

DROP POLICY IF EXISTS "Users can view farm sales" ON public."farm_sales";
CREATE POLICY "Users can view farm sales" ON public."farm_sales" FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));

DROP POLICY IF EXISTS "Coordinators can manage farm sales" ON public."farm_sales";
CREATE POLICY "Coordinators can manage farm sales" ON public."farm_sales" FOR ALL TO public USING ((EXISTS ( SELECT 1
   FROM farm_groups
  WHERE ((farm_groups.id = farm_sales.farm_id) AND (farm_groups.coordinator_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM farm_groups
  WHERE ((farm_groups.id = farm_sales.farm_id) AND (farm_groups.coordinator_id = auth.uid())))));

DROP POLICY IF EXISTS "Admins can manage farm sales" ON public."farm_sales";
CREATE POLICY "Admins can manage farm sales" ON public."farm_sales" FOR ALL TO public USING (is_admin(auth.uid())) WITH CHECK (is_admin(auth.uid()));

